<div id="view-content">
	<table class="available-shifts">
		<tbody>
		<?php foreach ($this->available as $shift): ?>
			<?php
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row % 2)
			{
				$class = 'odd';
			}
			else
			{
				$class = 'even';
			}
			
			?>
			
			<tr class="<?php print $class ?>">
			<td class="spacer">&nbsp;</td>
			<td class="time"><?php print $shift->getTimeString() ?></td>
			<td class="location"><?php print $shift->getLocation() ?></td>
			<td class="message"><?php print date('l', strtotime($shift->getDate())) ?></td>
			<td class="action"><a href="<?php print $this->url(array(
					'controller' => 'shift',
					'action'     => 'take',
					'id'         => $shift->getId(),
					), null, true) ?>">Take</a></td>
			</tr>
			<?php $row++; endforeach; ?>
		</tbody>
	</table>
</div>