<div id="view-content">
	<?php
	$yesterday = $this->timestamp - (60 * 60 * 24);
	$tomorrow = $this->timestamp + (60 * 60 * 24);
	?>
	<div class="date-picker">
		<a href="<?php print $this->url(array(
				'controller' => 'schedule',
				'action'     => 'index',
				'day'        => date('j', $yesterday),
				'month'      => date('m', $yesterday),
				'year'       => date('Y', $yesterday),
			))?>">&larr;</a>
		<?php print date('l, F j, Y', $this->timestamp) ?>
		<a href="<?php print $this->url(array(
				'controller' => 'schedule',
				'action'     => 'index',
				'day'        => date('j', $tomorrow),
				'month'      => date('m', $tomorrow),
				'year'       => date('Y', $tomorrow),
			))?>">&rarr;</a>
	</div>
	<table class="schedule">
		<thead>
			<tr>
				<td>Time</td>
				<td>Wireless Help Desk</td>
				<td>Lab Cleaning</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->schedule as $time => $shifts): ?>
			<?php
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row % 2)
			{
				$class = 'odd';
			}
			else
			{
				$class = 'even';
			}
			
			if (isset($shifts['WHD']))
			{
				$whd = $shifts['WHD'];
			}
			else if (isset($shifts['KEC']))
			{
				$whd = $shifts['KEC'];
			}
			
			if (isset($shifts['Lab']))
			{
				$lab = $shifts['Lab'];
			}
			else if (isset($shifts['Owen']))
			{
				$lab = $shifts['Owen'];
			}
			
			?>
			<tr class="<?php print $class ?>">
				<td><?php print $time ?></td>
				<?php if (isset($whd)): ?>
				<td><?php print $this->shiftText($whd, 'sched') ?></td>
				<?php else: ?>
				<td class="no-shift"><?php print '&nbsp' ?></td>
				<?php endif; ?>
				<?php if (isset($lab)): ?>
				<td><?php print $this->shiftText($lab, 'sched') ?></td>
				<?php else: ?>
				<td class="no-shift"><?php print '&nbsp' ?></td>
				<?php endif; ?>
			</tr>
			<?php unset($whd); unset($lab); $row++; ?>
			<?php endforeach ?>
		</tbody>
	</table>
</div>