<div id="view-content">
	<?php
	$date = date('Y-m-d');
	$time = time();
	?>
	<?php if (count($this->days) > 0): ?>
	<table class="available-shifts">
		<tbody>
			<?php foreach ($this->days as $day => $shifts): ?>
			<tr class="date">
				<?php if ($date == $day): ?>
				<td colspan="5">Today</td>
				<?php else: ?>
				<td colspan="5"><?php print date('l, F j, Y', strtotime($day)) ?></td>
				<?php endif; ?>
			</tr>
			<?php foreach ($shifts as $shift): ?>
			<?php
			
			$classes = array();
			
			if ($shift instanceof Application_Model_TempShift)
			{
				$temp = $shift;
				$shift = $temp->getShift();
			}
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row % 2)
			{
				$classes[] = 'odd';
			}
			else
			{
				$classes[] = 'even';
			}
			
			// If the user is not responsible for the shift
			if ((isset($temp)) and // There is a temp
				($temp->getTempConsultant() !== null) and // The shift has been taken
				($temp->getTempConsultant()->getId() != $this->user->getId())) // Not by you
			{
				$working = false;
				$classes[] = 'faded';
			}
			else
			{
				$working = true;
			}
			
			$class = implode(' ', $classes);
			?>
			
			<tr class="<?php print $class ?>">
			<td class="spacer">&nbsp;</td>
			<td class="time"><?php print $shift->getTimeString() ?></td>
			<td class="location"><?php print $shift->getLocation() ?></td>
			<td class="message"><?php
			
			$timeUntil = $shift->getStartTimestamp() - $time;
			
			// If the user is not responsible for the shift
			if ($working === false)
			{
				print $temp->getTempConsultant()->getName() . ' is covering this shift';
			}
			else
			{
				if ($timeUntil <= 0)
				{
					print '<strong>Right now</strong>';
				}
				else
				{
					// Less than 90 minutes until this shift
					if ($timeUntil < 60 * 90)
					{
						print '<em>In ' . floor($timeUntil / 60) . ' minutes</em>';
					}
					// Less than 24 hours until this shift?
					else if ($timeUntil < (60 * 60 * 24))
					{
						print '<em>In ' . floor($timeUntil / 60 / 60) . ' hours</em>';
					}
					else
					{
						print '&nbsp;';
					}
				}
			}
			
			?></td>
			<?php if (isset($temp)): ?>
			<td class="action"><?php print $this->shiftActionText($temp, 'personal') ?></td>
			<?php else: ?>			
			<td class="action"><?php print $this->shiftActionText($shift, 'personal') ?></td>
			<?php endif; ?>
			</tr>
			<?php unset($temp); $row++; endforeach; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php else: ?>
	<h2>No shifts remaining for this term</h2>
	<?php endif; ?>
</div>