<div id="view-content">
	<?php
	$date = date('Y-m-d');
	?>
	<?php if (count($this->days) > 0): ?>
	<table class="available-shifts">
		<tbody>
			<?php foreach ($this->days as $day => $shifts): ?>
			<tr class="date">
				<?php if ($date == $day): ?>
				<td colspan="5">Today</td>
				<?php else: ?>
				<td colspan="5"><?php print date('l, F j, Y', strtotime($day)) ?></td>
				<?php endif; ?>
			</tr>
			<?php foreach ($shifts as $shift): ?>
			<?php
			
			$classes = array();
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row++ % 2)
			{
				$classes[] = 'odd';
			}
			else
			{
				$classes[] = 'even';
			}
			
			if ($shift instanceof Application_Model_Meeting)
			{
				?>
				<tr class="<?php print $class ?>">
				<td class="spacer">&nbsp;</td>
				<td class="time"><?php print $shift->getTimeString() ?></td>
				<td class="location"><?php print $shift->getLocation() ?></td>
				<td class="message"><?php $this->timeUntil($shift) ?></td>
				<td class="action"><em>Meeting</em></td>
				</tr>
				<?php
				
				continue;
			}
			
			$event = $shift;
			if ($shift instanceof Application_Model_TempShift)
			{
				$temp = $shift;
				$shift = $temp->getShift();
			}
			
			// If the user is not responsible for the shift
			if ((isset($temp)) and // There is a temp
				($temp->getTempConsultant() !== null) and // The shift has been taken
				($temp->getTempConsultant()->getId() != $this->user->getId())) // Not by you
			{
				$classes[] = 'faded';
			}
			
			$class = implode(' ', $classes);
			?>
			
			<tr class="<?php print $class ?>">
			<td class="spacer">&nbsp;</td>
			<td class="time"><?php print $shift->getTimeString() ?></td>
			<td class="location"><?php print $shift->getLocation() ?></td>
			<td class="message"><?php print $this->timeUntil($event) ?></td>
			<?php if (isset($temp)): ?>
			<td class="action"><?php print $this->shiftActionText($temp, 'personal') ?></td>
			<?php else: ?>			
			<td class="action"><?php print $this->shiftActionText($shift, 'personal') ?></td>
			<?php endif; ?>
			</tr>
			<?php unset($temp); endforeach; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php else: ?>
	<h2>You have no shifts remaining this term</h2>
	<?php endif; ?>
</div>