<div id="view-content">
	<?php if ($this->user->isAdmin()): ?>
	<a href="<?php print $this->url(array(
			'controller' => 'consultants',
			'action'     => 'create',
		)); ?>">Create a new consultant</a><br />
	<br />
	<?php endif; ?>
	<table class="roster">
		<thead>
			<tr>
				<td>Name</td>
				<td>Email</td>
				<td>Phone</td>
			</tr>
		</thead>
		<tbody>
			<?php $i = 0 ?>
			<?php foreach ($this->consultants as $consultant): ?>
			<?php
			
			if ($i++ % 2)
			{
				$class = "odd";
			}
			else
			{
				$class = "even";
			}
			
			?>
			<tr class="<?php print $class ?>">
				<td><a href="<?php print $this->url(array(
					'controller' => 'consultants',
					'action'     => 'view',
					'id'         => $consultant->getId()
					), null, true) ?>"><?php print $consultant->getName() ?></a></td>
				<td><?php print $consultant->getEmail() ?></td>
				<td><?php print $consultant->getPhoneFormatted() ?></td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>