<?php print $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php print $this->headTitle() ?>
	<?php print $this->headLink() ?>
	<?php print $this->headStyle() ?>
	<?php print $this->headScript() ?>
</head>
<body>
<?php

if (Zend_Auth::getInstance()->hasIdentity())
{
	print '<a href="' . $this->url(array(
				'controller' => 'index',
				'action' => 'logout'
			),
			null, true) . '">Logout</a>';
}

// Print any messages sent from the controller
if (isset($this->messages))
{
	print '<ul>';
	foreach ($this->messages as $message)
	{
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}

print $this->layout()->content;

?>
</body>
</html>