<?php print $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php print $this->headTitle() ?>
	<?php print $this->headLink() ?>
	<?php print $this->headStyle() ?>
	<?php print $this->headScript() ?>
</head>
<body>
<div id="container">
<?php

$menuLinks = array();
$adminLinks = array();

if (Zend_Auth::getInstance()->hasIdentity())
{
	$user = Zend_Auth::getInstance()->getIdentity();
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'temp',
				'action'     => 'index'
			),
			null, true) . '">Available Shifts</a>';
	
	$menuLinks[] = array(
		'title' => 'Schedule',
		'links' => array(
			'<a href="' . $this->url(array(
				'controller' => 'schedule',
				'action'     => 'index',
				'day'        => date('j'),
				'month'      => date('m'),
				'year'       => date('y'),
			),
			null, true) . '">Today</a>',
			'<a href="' . $this->url(array(
				'controller' => 'index',
				'action'     => 'index',
				'month'      => date('m'),
				'year'       => date('y'),
			),
			null, true) . '">Month</a>',
		)
	);
	
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'schedule',
				'action'     => 'personal'
			),
			null, true) . '">Your schedule</a>';
	
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'consultants',
				'action'     => 'index'
			),
			null, true) . '">View roster</a>';
	
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'consultants',
				'action'     => 'edit',
				'id'         => $user->getId(),
			),
			null, true) . '">' . $user->getName() . '</a>';
	
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'index',
				'action'     => 'logout'
			),
			null, true) . '">Logout</a>';
	
	if (Zend_Auth::getInstance()->getIdentity()->isAdmin())
	{
		$adminLinks[] = '<a href="' . $this->url(array(
					'controller' => 'shift',
					'action'     => 'create'
				),
				null, true) . '">Create shifts</a>';
	
		$adminLinks[] = '<a href="' . $this->url(array(
					'controller' => 'shift',
					'action'     => 'assign'
				),
				null, true) . '">Assign shifts</a>';
	}
}

// Print the menu
print '<div class="nav"><ul id="menu" class="menu">';
foreach ($menuLinks as $link)
{
	if (is_array($link))
	{
		print '<li><span>' . $link['title'] . '</span>';
		print '<ul>';
		foreach ($link['links'] as $sub)
		{
			print "<li>{$sub}</li>";
		}
		print '</ul></li>';
	}
	else
	{
		print '<li class="nodiv">' . $link . '</li>';
	}
	
	print '</li>';
}
print '</ul></div>';

print   '<script type="text/javascript">var dropdown=' .
		'new TINY.dropdown.init("dropdown", {id:\'menu\', active:\'menuhover\'}); ' .
		'</script>';

print '<div id="content">';
// Print any messages sent from the controller
if (isset($this->messages))
{
	print '<ul>';
	foreach ($this->messages as $message)
	{
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}

print $this->layout()->content;
print '</div>'; // End content

?>
</div> <!-- End container -->
</body>
</html>
