<?php print $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php print $this->headTitle() ?>
	<?php print $this->headLink() ?>
	<?php print $this->headStyle() ?>
	<?php print $this->headScript() ?>
</head>
<body>
<?php

$menuLinks = array();

$menuLinks[] = '<a href="' . $this->url(array(
		'controller' => 'index',
		'action' => 'index'),
		null, true) . '">Calendar</a>';

$menuLinks[] = '<a href="' . $this->url(array(
		'controller' => 'schedule',
		'action' => 'index'),
		null, true) . '">Today\'s schedule</a>';

$menuLinks[] = '<a href="' . $this->url(array(
		'controller' => 'consultants',
		'action' => 'index'),
		null, true) . '">View roster</a>';

if (Zend_Auth::getInstance()->hasIdentity())
{
	if (Zend_Auth::getInstance()->getIdentity()->isAdmin())
	{
		$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'shift',
				'action' => 'create'),
				null, true) . '">Create shifts</a>';
		
		$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'shift',
				'action' => 'assign'),
				null, true) . '">Assign shifts</a>';
	}
	
	$menuLinks[] = '<a href="' . $this->url(array(
				'controller' => 'index',
				'action' => 'logout'
			),
			null, true) . '">Logout</a>';
}

// Print all menu links with a separator
print implode(' | ', $menuLinks);

// Print any messages sent from the controller
if (isset($this->messages))
{
	print '<ul>';
	foreach ($this->messages as $message)
	{
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}

print $this->layout()->content;

?>
</body>
</html>