<div id="view-content">
	<?php if (count($this->days) > 0): ?>
	<table class="available-shifts">
		<tbody>
			<?php foreach ($this->days as $day => $temps): ?>
			<tr class="date">
				<?php if (date('Y-m-d') == $day): ?>
				<td colspan="5">Today</td>
				<?php else: ?>
				<td colspan="5"><?php print date('l, F j, Y', strtotime($day)) ?></td>
				<?php endif; ?>
			</tr>
			<?php foreach ($temps as $temp): ?>
			<?php
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row % 2)
			{
				$class = 'odd';
			}
			else
			{
				$class = 'even';
			}
			
			?>
			
			<tr class="<?php print $class ?>">
			<td class="spacer">&nbsp;</td>
			<td class="time"><?php print $temp->getShift()->getTimeString() ?></td>
			<td class="location"><?php print $temp->getShift()->getLocation() ?></td>
			<td class="message"><?php
			
			$timeUntil = $temp->getShift()->getStartTimestamp() - time();
			
			// Less than 90 minutes until this shift
			if ($timeUntil < 60 * 90)
			{
				if ($temp->getShift()->getConsultant() !== null)
				{
					$name = $temp->getShift()->getConsultant()->getFirstName();
					$link = '<a href="' . $this->url(array(
						'controller' => 'consultants',
						'action'     => 'view',
						'id'         => $temp->getShift()->getConsultant()->getId(),
					), null, true) . '">' . $name . '</a>';
					print "<strong>{$link} needs a temp " .
							'in ' . floor($timeUntil / 60) . ' minutes</strong>';
				}
				else
				{
					print '<strong>In ' . floor($timeUntil / 60) . ' minutes</strong>';
				}
			}
			// Less than 24 hours until this shift?
			else if ($timeUntil < (60 * 60 * 24))
			{
				if ($temp->getShift()->getConsultant() !== null)
				{
					$name = $temp->getShift()->getConsultant()->getFirstName();
					$link = '<a href="' . $this->url(array(
						'controller' => 'consultants',
						'action'     => 'view',
						'id'         => $temp->getShift()->getConsultant()->getId(),
					), null, true) . '">' . $name . '</a>';
					print "<strong>{$link} needs a temp " .
							'in ' . floor($timeUntil / 60 / 60) . ' hours</strong>';
				}
				else
				{
					print '<strong>In ' . floor($timeUntil / 60 / 60) . ' hours</strong>';
				}
			}
			else
			{
				if ($temp->getShift()->getConsultant() !== null)
				{
					$name = $temp->getShift()->getConsultant()->getFirstName();
					$link = '<a href="' . $this->url(array(
						'controller' => 'consultants',
						'action'     => 'view',
						'id'         => $temp->getShift()->getConsultant()->getId(),
					), null, true) . '">' . $name . '</a>';
					print "<em>{$link} needs a temp</em>";
				}
				else
				{
					print "<em>Not yet filled!</em>";
				}
			}
			
			?></td>
			<?php if (($temp->getShift()->getConsultant() !== null) and
					  ($temp->getShift()->getConsultant()->getId() == $this->user->getId())): ?>
			<td class="action"><a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'cancel',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Cancel</a></td>
			<?php else: ?>
			<td class="action"><a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'take',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Fill</a></td>
			<?php endif; ?>
			</tr>
			<?php $row++; endforeach; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php else: ?>
	<h2>No temp shifts available.</h2>
	<?php endif; ?>
</div>