<div id="view-content">
	<?php if (count($this->days) > 0): ?>
	<table class="available-shifts">
		<tbody>
			<?php foreach ($this->days as $day => $temps): ?>
			<tr class="date">
				<?php if (date('Y-m-d') == $day): ?>
				<td colspan="5">Today</td>
				<?php else: ?>
				<td colspan="5"><?php print date('l, F j, Y', strtotime($day)) ?></td>
				<?php endif; ?>
			</tr>
			<?php foreach ($temps as $temp): ?>
			<?php
			
			if (!isset($row))
			{
				$row = 0;
			}
			
			if ($row % 2)
			{
				$class = 'odd';
			}
			else
			{
				$class = 'even';
			}
			
			?>
			
			<tr class="<?php print $class ?>">
			<td class="spacer">&nbsp;</td>
			<td class="time"><?php print $temp->getShift()->getTimeString() ?></td>
			<td class="location"><?php print $temp->getShift()->getLocation() ?></td>
			<td class="message"><?php
			
			print $this->tempMessage($temp, $this->user);
			
			?></td>
			<?php if ($temp->getShift()->isOwnedBy($this->user)): ?>
			<td class="action"><a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'cancel',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Cancel</a></td>
			<?php elseif ($temp->isAssignedTo($this->user)): ?>
			<td class="action">
				<a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'take',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Accept</a>
				<a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'refuse',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Refuse</a></td>
			<?php elseif ($temp->isAssigned()): ?>
			<td class="action">&nbsp;</td>
			<?php else: ?>
			<td class="action"><a href="<?php print $this->url(array(
					'controller' => 'temp',
					'action'     => 'take',
					'id'         => $temp->getId(),
					'goto'       => 'temps',
					), null, true) ?>">Fill</a></td>
			<?php endif; ?>
			</tr>
			<?php $row++; endforeach; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php else: ?>
	<h2>No temp shifts available.</h2>
	<?php endif; ?>
</div>